
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xce\x8a4\xab\xec\x8d\x10\x926\xd94\xb6<U\x8a\xab'
    
_lr_action_items = {'$end':([1,2,3,4,6,],[-2,-1,0,-5,-3,]),'decimal_number_literal':([0,5,],[4,4,]),'plus_sign':([1,2,3,4,6,],[-2,-1,5,-5,5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Sum':([0,5,],[1,1,]),'DecimalNumberLiteral':([0,5,],[2,2,]),'Expression':([0,5,],[3,6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Expression","S'",1,None,None,None),
  ('Expression -> DecimalNumberLiteral','Expression',1,'p_Expression','parser.py',15),
  ('Expression -> Sum','Expression',1,'p_Expression','parser.py',16),
  ('Sum -> Expression plus_sign Expression','Sum',3,'p_Sum','parser.py',20),
  ('Literal -> DecimalNumberLiteral','Literal',1,'p_Literal','parser.py',26),
  ('DecimalNumberLiteral -> decimal_number_literal','DecimalNumberLiteral',1,'p_DecimalNumberLiteral','parser.py',39),
]
